# Generated by Django 4.2.2 on 2023-07-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
