# Generated by Django 4.2.2 on 2023-07-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_remove_profile_image_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nombre',
            field=models.CharField(default='Ingresar nombre', max_length=100),
            preserve_default=False,
        ),
    ]
